modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="${modLicense}"

[[mods]]
modId="malum"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthors}"
description='''${modDescription}'''

[[dependencies.malum]]
modId="neoforge"
type="required"
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"
[[dependencies.malum]]
modId="minecraft"
type="required"
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"
[[dependencies.malum]]
modId = "lodestone"
type="required"
versionRange = "[1.20.1-1.6.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.malum]]
modId = "curios"
type="required"
versionRange = "[5.7.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.malum]]
modId="fusion"
type="optional"
versionRange="[1.0.0,)"
ordering="NONE"
side="CLIENT"